import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest'

// Create a shared object that will be populated with mocks
const mockState = {
  lineup: {
    findFirst: vi.fn(),
    create: vi.fn(),
  },
  teamPlayer: {
    findMany: vi.fn(),
  },
}

// Before any imports, set up module mocks
vi.mock('@/lib/db', () => ({
  prisma: {
    lineup: {
      findFirst: (...args: any[]) => mockState.lineup.findFirst(...args),
      create: (...args: any[]) => mockState.lineup.create(...args),
    },
    teamPlayer: {
      findMany: (...args: any[]) => mockState.teamPlayer.findMany(...args),
    },
  },
}))

// Import after all mocks are set up
import { ensureLineups } from '@/lib/scoring/pipeline'

describe('ensureLineups - Unit Tests', () => {
  beforeEach(() => {
    vi.clearAllMocks()
  })

  afterEach(() => {
    vi.clearAllMocks()
  })

  // AC1.1: Team with previous GW lineup gets it cloned
  it('AC1.1: carries forward previous lineup when current GW has no lineup', async () => {
    const team = {
      id: 'team-1',
      name: 'Test Team',
      lineups: [], // No lineup for current GW
      league: { id: 'league-1' },
      chipUsages: [],
    }

    const prevLineup = {
      id: 'lineup-prev',
      teamId: 'team-1',
      gameweekId: 'gw-1',
      slots: [
        { id: 'slot-1', playerId: 'player-1', slotType: 'XI', role: 'CAPTAIN', benchPriority: null },
        { id: 'slot-2', playerId: 'player-2', slotType: 'XI', role: null, benchPriority: null },
        { id: 'slot-3', playerId: 'player-3', slotType: 'XI', role: 'VC', benchPriority: null },
        { id: 'slot-4', playerId: 'player-4', slotType: 'BENCH', role: null, benchPriority: 1 },
      ],
      gameweek: { number: 1 },
    }

    const currentSquad = [
      { playerId: 'player-1' },
      { playerId: 'player-2' },
      { playerId: 'player-3' },
      { playerId: 'player-4' },
    ]

    // Mock finding previous lineup
    mockState.lineup.findFirst.mockResolvedValueOnce(prevLineup)

    // Mock finding current squad
    mockState.teamPlayer.findMany.mockResolvedValueOnce(currentSquad)

    // Mock creating new lineup
    const newLineup = { id: 'lineup-new', teamId: 'team-1', gameweekId: 'gw-2' }
    mockState.lineup.create.mockResolvedValueOnce(newLineup)

    // Create a mock transaction client
    const mockTx = {
      lineup: {
        findFirst: mockState.lineup.findFirst,
        create: mockState.lineup.create,
      },
      teamPlayer: {
        findMany: mockState.teamPlayer.findMany,
      },
    } as any

    const result = await ensureLineups(mockTx, [team as any], 'gw-2')

    expect(result.carriedForward).toBe(1)
    expect(result.autoGenerated).toBe(0)

    // Verify lineup.create was called with correct data
    expect(mockState.lineup.create).toHaveBeenCalledOnce()
    const createCall = mockState.lineup.create.mock.calls[0][0]
    expect(createCall.data.teamId).toBe('team-1')
    expect(createCall.data.gameweekId).toBe('gw-2')

    // Verify slots were created
    expect(createCall.data.slots.createMany.data).toHaveLength(4)
    expect(createCall.data.slots.createMany.data[0]).toEqual({
      playerId: 'player-1',
      slotType: 'XI',
      role: 'CAPTAIN',
      benchPriority: null,
    })
  })

  // AC1.2: Most recent previous lineup is used
  it('AC1.2: uses the most recent previous lineup when multiple exist', async () => {
    const team = {
      id: 'team-2',
      name: 'Test Team 2',
      lineups: [], // No lineup for current GW
      league: { id: 'league-1' },
      chipUsages: [],
    }

    const recentLineup = {
      id: 'lineup-recent',
      teamId: 'team-2',
      gameweekId: 'gw-3',
      slots: [
        { id: 'slot-1', playerId: 'player-1', slotType: 'XI', role: null, benchPriority: null },
      ],
      gameweek: { number: 3 },
    }

    const currentSquad = [{ playerId: 'player-1' }]

    // Mock finding the most recent lineup (ordered by gameweek.number desc)
    mockState.lineup.findFirst.mockResolvedValueOnce(recentLineup)
    mockState.teamPlayer.findMany.mockResolvedValueOnce(currentSquad)
    mockState.lineup.create.mockResolvedValueOnce({ id: 'lineup-new' })

    const mockTx = {
      lineup: {
        findFirst: mockState.lineup.findFirst,
        create: mockState.lineup.create,
      },
      teamPlayer: {
        findMany: mockState.teamPlayer.findMany,
      },
    } as any

    await ensureLineups(mockTx, [team as any], 'gw-4')

    // Verify findFirst was called with correct orderBy
    expect(mockState.lineup.findFirst).toHaveBeenCalledOnce()
    const findCall = mockState.lineup.findFirst.mock.calls[0][0]
    expect(findCall.orderBy).toEqual({ gameweek: { number: 'desc' } })
  })

  // AC1.4: Team with existing lineup is skipped
  it('AC1.4: skips team with existing lineup for this GW', async () => {
    const team = {
      id: 'team-3',
      name: 'Test Team 3',
      lineups: [
        {
          id: 'lineup-existing',
          slots: [{ id: 'slot-1', playerId: 'player-1' }],
        },
      ], // Has lineup for current GW
      league: { id: 'league-1' },
      chipUsages: [],
    }

    const mockTx = {
      lineup: {
        findFirst: mockState.lineup.findFirst,
        create: mockState.lineup.create,
      },
      teamPlayer: {
        findMany: mockState.teamPlayer.findMany,
      },
    } as any

    const result = await ensureLineups(mockTx, [team as any], 'gw-2')

    expect(result.carriedForward).toBe(0)
    expect(result.autoGenerated).toBe(0)

    // Verify no queries were made
    expect(mockState.lineup.findFirst).not.toHaveBeenCalled()
    expect(mockState.lineup.create).not.toHaveBeenCalled()
  })

  // AC1.5: Players removed from squad are excluded
  it('AC1.5: excludes players removed from squad since previous lineup', async () => {
    const team = {
      id: 'team-4',
      name: 'Test Team 4',
      lineups: [],
      league: { id: 'league-1' },
      chipUsages: [],
    }

    const prevLineup = {
      id: 'lineup-prev',
      teamId: 'team-4',
      gameweekId: 'gw-1',
      slots: [
        { id: 'slot-1', playerId: 'player-1', slotType: 'XI', role: null, benchPriority: null },
        { id: 'slot-2', playerId: 'player-removed', slotType: 'XI', role: null, benchPriority: null },
        { id: 'slot-3', playerId: 'player-3', slotType: 'BENCH', role: null, benchPriority: 1 },
      ],
      gameweek: { number: 1 },
    }

    // Current squad only has 2 of the 3 previous players
    const currentSquad = [
      { playerId: 'player-1' },
      { playerId: 'player-3' },
    ]

    mockState.lineup.findFirst.mockResolvedValueOnce(prevLineup)
    mockState.teamPlayer.findMany.mockResolvedValueOnce(currentSquad)
    mockState.lineup.create.mockResolvedValueOnce({ id: 'lineup-new' })

    const mockTx = {
      lineup: {
        findFirst: mockState.lineup.findFirst,
        create: mockState.lineup.create,
      },
      teamPlayer: {
        findMany: mockState.teamPlayer.findMany,
      },
    } as any

    await ensureLineups(mockTx, [team as any], 'gw-2')

    // Verify lineup.create was called with only 2 slots
    expect(mockState.lineup.create).toHaveBeenCalledOnce()
    const createCall = mockState.lineup.create.mock.calls[0][0]
    expect(createCall.data.slots.createMany.data).toHaveLength(2)

    // Verify only active players are in slots
    const playerIds = createCall.data.slots.createMany.data.map((s: any) => s.playerId)
    expect(playerIds).toContain('player-1')
    expect(playerIds).toContain('player-3')
    expect(playerIds).not.toContain('player-removed')
  })

  // AC1.3: Lineup create called with correct data structure
  it('AC1.3: creates real Lineup and LineupSlot records via tx.lineup.create()', async () => {
    const team = {
      id: 'team-5',
      name: 'Test Team 5',
      lineups: [],
      league: { id: 'league-1' },
      chipUsages: [],
    }

    const prevLineup = {
      id: 'lineup-prev',
      teamId: 'team-5',
      gameweekId: 'gw-1',
      slots: [
        { id: 'slot-1', playerId: 'player-1', slotType: 'XI', role: 'CAPTAIN', benchPriority: null },
      ],
      gameweek: { number: 1 },
    }

    mockState.lineup.findFirst.mockResolvedValueOnce(prevLineup)
    mockState.teamPlayer.findMany.mockResolvedValueOnce([{ playerId: 'player-1' }])
    mockState.lineup.create.mockResolvedValueOnce({ id: 'lineup-new' })

    const mockTx = {
      lineup: {
        findFirst: mockState.lineup.findFirst,
        create: mockState.lineup.create,
      },
      teamPlayer: {
        findMany: mockState.teamPlayer.findMany,
      },
    } as any

    await ensureLineups(mockTx, [team as any], 'gw-2')

    expect(mockState.lineup.create).toHaveBeenCalledOnce()
    const createCall = mockState.lineup.create.mock.calls[0][0]

    // Verify structure matches Prisma nested create
    expect(createCall.data).toEqual({
      teamId: 'team-5',
      gameweekId: 'gw-2',
      slots: {
        createMany: {
          data: [
            {
              playerId: 'player-1',
              slotType: 'XI',
              role: 'CAPTAIN',
              benchPriority: null,
            },
          ],
        },
      },
    })
  })
})
