import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest'

// Create a shared object that will be populated with mocks
const mockState = {
  lineup: {
    findFirst: vi.fn(),
    create: vi.fn(),
  },
  teamPlayer: {
    findMany: vi.fn(),
  },
}

// Before any imports, set up module mocks
vi.mock('@/lib/db', () => ({
  prisma: {
    lineup: {
      findFirst: (...args: any[]) => mockState.lineup.findFirst(...args),
      create: (...args: any[]) => mockState.lineup.create(...args),
    },
    teamPlayer: {
      findMany: (...args: any[]) => mockState.teamPlayer.findMany(...args),
    },
  },
}))

// Import after all mocks are set up
import { ensureLineups } from '@/lib/scoring/pipeline'

describe('ensureLineups - Unit Tests', () => {
  beforeEach(() => {
    vi.clearAllMocks()
  })

  // AC1.1: Team with previous GW lineup gets it cloned
  it('AC1.1: carries forward previous lineup when current GW has no lineup', async () => {
    const team = {
      id: 'team-1',
      name: 'Test Team',
      lineups: [], // No lineup for current GW
      league: { id: 'league-1' },
      chipUsages: [],
    }

    const prevLineup = {
      id: 'lineup-prev',
      teamId: 'team-1',
      gameweekId: 'gw-1',
      slots: [
        { id: 'slot-1', playerId: 'player-1', slotType: 'XI', role: 'CAPTAIN', benchPriority: null },
        { id: 'slot-2', playerId: 'player-2', slotType: 'XI', role: null, benchPriority: null },
        { id: 'slot-3', playerId: 'player-3', slotType: 'XI', role: 'VC', benchPriority: null },
        { id: 'slot-4', playerId: 'player-4', slotType: 'BENCH', role: null, benchPriority: 1 },
      ],
      gameweek: { number: 1 },
    }

    const currentSquad = [
      { playerId: 'player-1' },
      { playerId: 'player-2' },
      { playerId: 'player-3' },
      { playerId: 'player-4' },
    ]

    // Mock finding previous lineup
    mockState.lineup.findFirst.mockResolvedValueOnce(prevLineup)

    // Mock finding current squad
    mockState.teamPlayer.findMany.mockResolvedValueOnce(currentSquad)

    // Mock creating new lineup
    const newLineup = { id: 'lineup-new', teamId: 'team-1', gameweekId: 'gw-2' }
    mockState.lineup.create.mockResolvedValueOnce(newLineup)

    // Create a mock transaction client
    const mockTx = {
      lineup: {
        findFirst: mockState.lineup.findFirst,
        create: mockState.lineup.create,
      },
      teamPlayer: {
        findMany: mockState.teamPlayer.findMany,
      },
    } as any

    const result = await ensureLineups(mockTx, [team as any], 'gw-2')

    expect(result.carriedForward).toBe(1)
    expect(result.autoGenerated).toBe(0)

    // Verify lineup.create was called with correct data
    expect(mockState.lineup.create).toHaveBeenCalledOnce()
    const createCall = mockState.lineup.create.mock.calls[0][0]
    expect(createCall.data.teamId).toBe('team-1')
    expect(createCall.data.gameweekId).toBe('gw-2')

    // Verify slots were created
    expect(createCall.data.slots.createMany.data).toHaveLength(4)
    expect(createCall.data.slots.createMany.data[0]).toEqual({
      playerId: 'player-1',
      slotType: 'XI',
      role: 'CAPTAIN',
      benchPriority: null,
    })
  })

  // AC1.2: Most recent previous lineup is used
  it('AC1.2: uses the most recent previous lineup when multiple exist', async () => {
    const team = {
      id: 'team-2',
      name: 'Test Team 2',
      lineups: [], // No lineup for current GW
      league: { id: 'league-1' },
      chipUsages: [],
    }

    const recentLineup = {
      id: 'lineup-recent',
      teamId: 'team-2',
      gameweekId: 'gw-3',
      slots: [
        { id: 'slot-1', playerId: 'player-1', slotType: 'XI', role: null, benchPriority: null },
      ],
      gameweek: { number: 3 },
    }

    const currentSquad = [{ playerId: 'player-1' }]

    // Mock finding the most recent lineup (ordered by gameweek.number desc)
    mockState.lineup.findFirst.mockResolvedValueOnce(recentLineup)
    mockState.teamPlayer.findMany.mockResolvedValueOnce(currentSquad)
    mockState.lineup.create.mockResolvedValueOnce({ id: 'lineup-new' })

    const mockTx = {
      lineup: {
        findFirst: mockState.lineup.findFirst,
        create: mockState.lineup.create,
      },
      teamPlayer: {
        findMany: mockState.teamPlayer.findMany,
      },
    } as any

    await ensureLineups(mockTx, [team as any], 'gw-4')

    // Verify findFirst was called with correct orderBy
    expect(mockState.lineup.findFirst).toHaveBeenCalledOnce()
    const findCall = mockState.lineup.findFirst.mock.calls[0][0]
    expect(findCall.orderBy).toEqual({ gameweek: { number: 'desc' } })
  })

  // AC1.4: Team with existing lineup is skipped
  it('AC1.4: skips team with existing lineup for this GW', async () => {
    const team = {
      id: 'team-3',
      name: 'Test Team 3',
      lineups: [
        {
          id: 'lineup-existing',
          slots: [{ id: 'slot-1', playerId: 'player-1' }],
        },
      ], // Has lineup for current GW
      league: { id: 'league-1' },
      chipUsages: [],
    }

    const mockTx = {
      lineup: {
        findFirst: mockState.lineup.findFirst,
        create: mockState.lineup.create,
      },
      teamPlayer: {
        findMany: mockState.teamPlayer.findMany,
      },
    } as any

    const result = await ensureLineups(mockTx, [team as any], 'gw-2')

    expect(result.carriedForward).toBe(0)
    expect(result.autoGenerated).toBe(0)

    // Verify no queries were made
    expect(mockState.lineup.findFirst).not.toHaveBeenCalled()
    expect(mockState.lineup.create).not.toHaveBeenCalled()
  })

  // AC1.5: Players removed from squad are excluded
  it('AC1.5: excludes players removed from squad since previous lineup', async () => {
    const team = {
      id: 'team-4',
      name: 'Test Team 4',
      lineups: [],
      league: { id: 'league-1' },
      chipUsages: [],
    }

    const prevLineup = {
      id: 'lineup-prev',
      teamId: 'team-4',
      gameweekId: 'gw-1',
      slots: [
        { id: 'slot-1', playerId: 'player-1', slotType: 'XI', role: null, benchPriority: null },
        { id: 'slot-2', playerId: 'player-removed', slotType: 'XI', role: null, benchPriority: null },
        { id: 'slot-3', playerId: 'player-3', slotType: 'BENCH', role: null, benchPriority: 1 },
      ],
      gameweek: { number: 1 },
    }

    // Current squad only has 2 of the 3 previous players
    const currentSquad = [
      { playerId: 'player-1' },
      { playerId: 'player-3' },
    ]

    mockState.lineup.findFirst.mockResolvedValueOnce(prevLineup)
    mockState.teamPlayer.findMany.mockResolvedValueOnce(currentSquad)
    mockState.lineup.create.mockResolvedValueOnce({ id: 'lineup-new' })

    const mockTx = {
      lineup: {
        findFirst: mockState.lineup.findFirst,
        create: mockState.lineup.create,
      },
      teamPlayer: {
        findMany: mockState.teamPlayer.findMany,
      },
    } as any

    await ensureLineups(mockTx, [team as any], 'gw-2')

    // Verify lineup.create was called with only 2 slots
    expect(mockState.lineup.create).toHaveBeenCalledOnce()
    const createCall = mockState.lineup.create.mock.calls[0][0]
    expect(createCall.data.slots.createMany.data).toHaveLength(2)

    // Verify only active players are in slots
    const playerIds = createCall.data.slots.createMany.data.map((s: any) => s.playerId)
    expect(playerIds).toContain('player-1')
    expect(playerIds).toContain('player-3')
    expect(playerIds).not.toContain('player-removed')
  })

  // AC2.1: Auto-generate from squad
  it('AC2.1: auto-generates lineup from squad when no previous lineups exist', async () => {
    const team = {
      id: 'team-autogen-1',
      name: 'Test Team AutoGen',
      lineups: [], // No previous lineups
      league: { id: 'league-1' },
      chipUsages: [],
    }

    // Mock team players with varying purchase prices
    const mockTeamPlayers = [
      { id: 'p1', playerId: 'pid1', teamId: 'team-autogen-1', leagueId: 'league1', purchasePrice: 10.0, player: { id: 'pid1', fullname: 'Player 1' } },
      { id: 'p2', playerId: 'pid2', teamId: 'team-autogen-1', leagueId: 'league1', purchasePrice: 9.5, player: { id: 'pid2', fullname: 'Player 2' } },
      { id: 'p3', playerId: 'pid3', teamId: 'team-autogen-1', leagueId: 'league1', purchasePrice: 9.0, player: { id: 'pid3', fullname: 'Player 3' } },
      { id: 'p4', playerId: 'pid4', teamId: 'team-autogen-1', leagueId: 'league1', purchasePrice: 8.5, player: { id: 'pid4', fullname: 'Player 4' } },
      { id: 'p5', playerId: 'pid5', teamId: 'team-autogen-1', leagueId: 'league1', purchasePrice: 8.0, player: { id: 'pid5', fullname: 'Player 5' } },
      { id: 'p6', playerId: 'pid6', teamId: 'team-autogen-1', leagueId: 'league1', purchasePrice: 7.5, player: { id: 'pid6', fullname: 'Player 6' } },
      { id: 'p7', playerId: 'pid7', teamId: 'team-autogen-1', leagueId: 'league1', purchasePrice: 7.0, player: { id: 'pid7', fullname: 'Player 7' } },
      { id: 'p8', playerId: 'pid8', teamId: 'team-autogen-1', leagueId: 'league1', purchasePrice: 6.5, player: { id: 'pid8', fullname: 'Player 8' } },
      { id: 'p9', playerId: 'pid9', teamId: 'team-autogen-1', leagueId: 'league1', purchasePrice: 6.0, player: { id: 'pid9', fullname: 'Player 9' } },
      { id: 'p10', playerId: 'pid10', teamId: 'team-autogen-1', leagueId: 'league1', purchasePrice: 5.5, player: { id: 'pid10', fullname: 'Player 10' } },
      { id: 'p11', playerId: 'pid11', teamId: 'team-autogen-1', leagueId: 'league1', purchasePrice: 5.0, player: { id: 'pid11', fullname: 'Player 11' } },
      { id: 'p12', playerId: 'pid12', teamId: 'team-autogen-1', leagueId: 'league1', purchasePrice: 4.5, player: { id: 'pid12', fullname: 'Player 12' } },
      { id: 'p13', playerId: 'pid13', teamId: 'team-autogen-1', leagueId: 'league1', purchasePrice: 4.0, player: { id: 'pid13', fullname: 'Player 13' } },
      { id: 'p14', playerId: 'pid14', teamId: 'team-autogen-1', leagueId: 'league1', purchasePrice: 3.5, player: { id: 'pid14', fullname: 'Player 14' } },
      { id: 'p15', playerId: 'pid15', teamId: 'team-autogen-1', leagueId: 'league1', purchasePrice: 3.0, player: { id: 'pid15', fullname: 'Player 15' } },
    ]

    mockState.lineup.findFirst.mockResolvedValueOnce(null) // No previous lineup
    mockState.teamPlayer.findMany.mockResolvedValueOnce(mockTeamPlayers)

    // Mock creating new auto-generated lineup
    const newLineup = { id: 'lineup-autogen', teamId: 'team-autogen-1', gameweekId: 'gw-2' }
    mockState.lineup.create.mockResolvedValueOnce(newLineup)

    // Create a mock transaction client
    const mockTx = {
      lineup: {
        findFirst: mockState.lineup.findFirst,
        create: mockState.lineup.create,
      },
      teamPlayer: {
        findMany: mockState.teamPlayer.findMany,
      },
    } as any

    const result = await ensureLineups(mockTx, [team as any], 'gw-2')

    expect(result.autoGenerated).toBe(1)
    expect(result.carriedForward).toBe(0)

    // Verify lineup.create was called with correct data
    expect(mockState.lineup.create).toHaveBeenCalledOnce()
    const createCall = mockState.lineup.create.mock.calls[0][0]
    expect(createCall.data.teamId).toBe('team-autogen-1')
    expect(createCall.data.gameweekId).toBe('gw-2')

    // Verify 15 slots were created
    expect(createCall.data.slots.createMany.data).toHaveLength(15)
  })

  // AC2.2: XI/Bench by purchasePrice
  it('AC2.2: assigns XI (top 11) and BENCH (bottom 4) by purchase price', async () => {
    const team = {
      id: 'team-split',
      name: 'Test Team Split',
      lineups: [],
      league: { id: 'league-1' },
      chipUsages: [],
    }

    const mockTeamPlayers = [
      { id: 'p1', playerId: 'pid1', purchasePrice: 15.0, player: { id: 'pid1', fullname: 'Player 1' } },
      { id: 'p2', playerId: 'pid2', purchasePrice: 14.0, player: { id: 'pid2', fullname: 'Player 2' } },
      { id: 'p3', playerId: 'pid3', purchasePrice: 13.0, player: { id: 'pid3', fullname: 'Player 3' } },
      { id: 'p4', playerId: 'pid4', purchasePrice: 12.0, player: { id: 'pid4', fullname: 'Player 4' } },
      { id: 'p5', playerId: 'pid5', purchasePrice: 11.0, player: { id: 'pid5', fullname: 'Player 5' } },
      { id: 'p6', playerId: 'pid6', purchasePrice: 10.0, player: { id: 'pid6', fullname: 'Player 6' } },
      { id: 'p7', playerId: 'pid7', purchasePrice: 9.0, player: { id: 'pid7', fullname: 'Player 7' } },
      { id: 'p8', playerId: 'pid8', purchasePrice: 8.0, player: { id: 'pid8', fullname: 'Player 8' } },
      { id: 'p9', playerId: 'pid9', purchasePrice: 7.0, player: { id: 'pid9', fullname: 'Player 9' } },
      { id: 'p10', playerId: 'pid10', purchasePrice: 6.0, player: { id: 'pid10', fullname: 'Player 10' } },
      { id: 'p11', playerId: 'pid11', purchasePrice: 5.0, player: { id: 'pid11', fullname: 'Player 11' } },
      { id: 'p12', playerId: 'pid12', purchasePrice: 4.0, player: { id: 'pid12', fullname: 'Player 12' } },
      { id: 'p13', playerId: 'pid13', purchasePrice: 3.0, player: { id: 'pid13', fullname: 'Player 13' } },
      { id: 'p14', playerId: 'pid14', purchasePrice: 2.0, player: { id: 'pid14', fullname: 'Player 14' } },
      { id: 'p15', playerId: 'pid15', purchasePrice: 1.0, player: { id: 'pid15', fullname: 'Player 15' } },
    ]

    mockState.lineup.findFirst.mockResolvedValueOnce(null)
    mockState.teamPlayer.findMany.mockResolvedValueOnce(mockTeamPlayers)
    mockState.lineup.create.mockResolvedValueOnce({ id: 'lineup-split' })

    const mockTx = {
      lineup: {
        findFirst: mockState.lineup.findFirst,
        create: mockState.lineup.create,
      },
      teamPlayer: {
        findMany: mockState.teamPlayer.findMany,
      },
    } as any

    await ensureLineups(mockTx, [team as any], 'gw-2')

    const createCall = mockState.lineup.create.mock.calls[0][0]
    const slots = createCall.data.slots.createMany.data

    const xiSlots = slots.filter((s: any) => s.slotType === 'XI')
    const benchSlots = slots.filter((s: any) => s.slotType === 'BENCH')

    expect(xiSlots).toHaveLength(11)
    expect(benchSlots).toHaveLength(4)

    // Verify top 11 have slotType 'XI'
    xiSlots.forEach((slot: any) => {
      expect(slot.slotType).toBe('XI')
    })

    // Verify bottom 4 have slotType 'BENCH'
    benchSlots.forEach((slot: any) => {
      expect(slot.slotType).toBe('BENCH')
    })
  })

  // AC2.3: Captain = highest price
  it('AC2.3: assigns CAPTAIN to highest price and VC to second highest', async () => {
    const team = {
      id: 'team-captain',
      name: 'Test Team Captain',
      lineups: [],
      league: { id: 'league-1' },
      chipUsages: [],
    }

    const mockTeamPlayers = [
      { id: 'p1', playerId: 'pid1', purchasePrice: 15.0, player: { id: 'pid1', fullname: 'Player 1' } },
      { id: 'p2', playerId: 'pid2', purchasePrice: 14.0, player: { id: 'pid2', fullname: 'Player 2' } },
      { id: 'p3', playerId: 'pid3', purchasePrice: 13.0, player: { id: 'pid3', fullname: 'Player 3' } },
      { id: 'p4', playerId: 'pid4', purchasePrice: 12.0, player: { id: 'pid4', fullname: 'Player 4' } },
      { id: 'p5', playerId: 'pid5', purchasePrice: 11.0, player: { id: 'pid5', fullname: 'Player 5' } },
      { id: 'p6', playerId: 'pid6', purchasePrice: 10.0, player: { id: 'pid6', fullname: 'Player 6' } },
      { id: 'p7', playerId: 'pid7', purchasePrice: 9.0, player: { id: 'pid7', fullname: 'Player 7' } },
      { id: 'p8', playerId: 'pid8', purchasePrice: 8.0, player: { id: 'pid8', fullname: 'Player 8' } },
      { id: 'p9', playerId: 'pid9', purchasePrice: 7.0, player: { id: 'pid9', fullname: 'Player 9' } },
      { id: 'p10', playerId: 'pid10', purchasePrice: 6.0, player: { id: 'pid10', fullname: 'Player 10' } },
      { id: 'p11', playerId: 'pid11', purchasePrice: 5.0, player: { id: 'pid11', fullname: 'Player 11' } },
      { id: 'p12', playerId: 'pid12', purchasePrice: 4.0, player: { id: 'pid12', fullname: 'Player 12' } },
      { id: 'p13', playerId: 'pid13', purchasePrice: 3.0, player: { id: 'pid13', fullname: 'Player 13' } },
      { id: 'p14', playerId: 'pid14', purchasePrice: 2.0, player: { id: 'pid14', fullname: 'Player 14' } },
      { id: 'p15', playerId: 'pid15', purchasePrice: 1.0, player: { id: 'pid15', fullname: 'Player 15' } },
    ]

    mockState.lineup.findFirst.mockResolvedValueOnce(null)
    mockState.teamPlayer.findMany.mockResolvedValueOnce(mockTeamPlayers)
    mockState.lineup.create.mockResolvedValueOnce({ id: 'lineup-captain' })

    const mockTx = {
      lineup: {
        findFirst: mockState.lineup.findFirst,
        create: mockState.lineup.create,
      },
      teamPlayer: {
        findMany: mockState.teamPlayer.findMany,
      },
    } as any

    await ensureLineups(mockTx, [team as any], 'gw-2')

    const createCall = mockState.lineup.create.mock.calls[0][0]
    const slots = createCall.data.slots.createMany.data

    const captain = slots.find((s: any) => s.role === 'CAPTAIN')
    const vc = slots.find((s: any) => s.role === 'VC')

    expect(captain?.playerId).toBe('pid1')
    expect(captain?.slotType).toBe('XI')
    expect(vc?.playerId).toBe('pid2')
    expect(vc?.slotType).toBe('XI')
  })

  // AC2.4: Bench priority order
  it('AC2.4: assigns bench priorities 1-4 in descending price order', async () => {
    const team = {
      id: 'team-bench',
      name: 'Test Team Bench',
      lineups: [],
      league: { id: 'league-1' },
      chipUsages: [],
    }

    const mockTeamPlayers = [
      { id: 'p1', playerId: 'pid1', purchasePrice: 15.0, player: { id: 'pid1', fullname: 'Player 1' } },
      { id: 'p2', playerId: 'pid2', purchasePrice: 14.0, player: { id: 'pid2', fullname: 'Player 2' } },
      { id: 'p3', playerId: 'pid3', purchasePrice: 13.0, player: { id: 'pid3', fullname: 'Player 3' } },
      { id: 'p4', playerId: 'pid4', purchasePrice: 12.0, player: { id: 'pid4', fullname: 'Player 4' } },
      { id: 'p5', playerId: 'pid5', purchasePrice: 11.0, player: { id: 'pid5', fullname: 'Player 5' } },
      { id: 'p6', playerId: 'pid6', purchasePrice: 10.0, player: { id: 'pid6', fullname: 'Player 6' } },
      { id: 'p7', playerId: 'pid7', purchasePrice: 9.0, player: { id: 'pid7', fullname: 'Player 7' } },
      { id: 'p8', playerId: 'pid8', purchasePrice: 8.0, player: { id: 'pid8', fullname: 'Player 8' } },
      { id: 'p9', playerId: 'pid9', purchasePrice: 7.0, player: { id: 'pid9', fullname: 'Player 9' } },
      { id: 'p10', playerId: 'pid10', purchasePrice: 6.0, player: { id: 'pid10', fullname: 'Player 10' } },
      { id: 'p11', playerId: 'pid11', purchasePrice: 5.0, player: { id: 'pid11', fullname: 'Player 11' } },
      { id: 'p12', playerId: 'pid12', purchasePrice: 4.0, player: { id: 'pid12', fullname: 'Player 12' } },
      { id: 'p13', playerId: 'pid13', purchasePrice: 3.0, player: { id: 'pid13', fullname: 'Player 13' } },
      { id: 'p14', playerId: 'pid14', purchasePrice: 2.0, player: { id: 'pid14', fullname: 'Player 14' } },
      { id: 'p15', playerId: 'pid15', purchasePrice: 1.0, player: { id: 'pid15', fullname: 'Player 15' } },
    ]

    mockState.lineup.findFirst.mockResolvedValueOnce(null)
    mockState.teamPlayer.findMany.mockResolvedValueOnce(mockTeamPlayers)
    mockState.lineup.create.mockResolvedValueOnce({ id: 'lineup-bench' })

    const mockTx = {
      lineup: {
        findFirst: mockState.lineup.findFirst,
        create: mockState.lineup.create,
      },
      teamPlayer: {
        findMany: mockState.teamPlayer.findMany,
      },
    } as any

    await ensureLineups(mockTx, [team as any], 'gw-2')

    const createCall = mockState.lineup.create.mock.calls[0][0]
    const slots = createCall.data.slots.createMany.data

    const benchSlots = slots.filter((s: any) => s.slotType === 'BENCH')
    const priorities = benchSlots.map((s: any) => s.benchPriority)

    expect(priorities).toEqual([1, 2, 3, 4])
    expect(benchSlots[0].playerId).toBe('pid12') // price 4.0
    expect(benchSlots[1].playerId).toBe('pid13') // price 3.0
    expect(benchSlots[2].playerId).toBe('pid14') // price 2.0
    expect(benchSlots[3].playerId).toBe('pid15') // price 1.0
  })

  // AC2.5: Skip team with no squad
  it('AC2.5: skips team with empty squad, no lineup created', async () => {
    const team = {
      id: 'team-nosquad',
      name: 'Test Team NoSquad',
      lineups: [],
      league: { id: 'league-1' },
      chipUsages: [],
    }

    mockState.lineup.findFirst.mockResolvedValueOnce(null)
    mockState.teamPlayer.findMany.mockResolvedValueOnce([]) // Empty squad

    const mockTx = {
      lineup: {
        findFirst: mockState.lineup.findFirst,
        create: mockState.lineup.create,
      },
      teamPlayer: {
        findMany: mockState.teamPlayer.findMany,
      },
    } as any

    const result = await ensureLineups(mockTx, [team as any], 'gw-2')

    expect(result.autoGenerated).toBe(0)
    expect(mockState.lineup.create).not.toHaveBeenCalled()
  })

  // AC2.6: Carry-forward takes precedence over auto-generate
  it('AC2.6: carry-forward takes precedence over auto-generate when both are possible', async () => {
    const team = {
      id: 'team-precedence',
      name: 'Test Team Precedence',
      lineups: [], // Will have carry-forward but squad also exists
      league: { id: 'league-1' },
      chipUsages: [],
    }

    const prevLineup = {
      id: 'lineup-prev',
      teamId: 'team-precedence',
      gameweekId: 'gw-1',
      slots: [
        { id: 'slot-1', playerId: 'player-prev', slotType: 'XI', role: 'CAPTAIN', benchPriority: null },
      ],
      gameweek: { number: 1 },
    }

    // Even though there's a full squad, carry-forward should take precedence
    const fullSquad = [
      { playerId: 'player-new' },
      { playerId: 'player-prev' },
    ]

    mockState.lineup.findFirst.mockResolvedValueOnce(prevLineup) // Found previous lineup
    mockState.teamPlayer.findMany.mockResolvedValueOnce(fullSquad) // Squad exists
    mockState.lineup.create.mockResolvedValueOnce({ id: 'lineup-new' })

    const mockTx = {
      lineup: {
        findFirst: mockState.lineup.findFirst,
        create: mockState.lineup.create,
      },
      teamPlayer: {
        findMany: mockState.teamPlayer.findMany,
      },
    } as any

    const result = await ensureLineups(mockTx, [team as any], 'gw-2')

    // Verify: carry-forward was done, not auto-generate
    expect(result.carriedForward).toBe(1)
    expect(result.autoGenerated).toBe(0)

    // Verify slots were created based on previous lineup, not auto-gen
    expect(mockState.lineup.create).toHaveBeenCalledOnce()
    const createCall = mockState.lineup.create.mock.calls[0][0]
    expect(createCall.data.slots.createMany.data[0].playerId).toBe('player-prev')
  })

  // AC1.3: Lineup create called with correct data structure
  it('AC1.3: creates real Lineup and LineupSlot records via tx.lineup.create()', async () => {
    const team = {
      id: 'team-5',
      name: 'Test Team 5',
      lineups: [],
      league: { id: 'league-1' },
      chipUsages: [],
    }

    const prevLineup = {
      id: 'lineup-prev',
      teamId: 'team-5',
      gameweekId: 'gw-1',
      slots: [
        { id: 'slot-1', playerId: 'player-1', slotType: 'XI', role: 'CAPTAIN', benchPriority: null },
      ],
      gameweek: { number: 1 },
    }

    mockState.lineup.findFirst.mockResolvedValueOnce(prevLineup)
    mockState.teamPlayer.findMany.mockResolvedValueOnce([{ playerId: 'player-1' }])
    mockState.lineup.create.mockResolvedValueOnce({ id: 'lineup-new' })

    const mockTx = {
      lineup: {
        findFirst: mockState.lineup.findFirst,
        create: mockState.lineup.create,
      },
      teamPlayer: {
        findMany: mockState.teamPlayer.findMany,
      },
    } as any

    await ensureLineups(mockTx, [team as any], 'gw-2')

    expect(mockState.lineup.create).toHaveBeenCalledOnce()
    const createCall = mockState.lineup.create.mock.calls[0][0]

    // Verify structure matches Prisma nested create
    expect(createCall.data).toEqual({
      teamId: 'team-5',
      gameweekId: 'gw-2',
      slots: {
        createMany: {
          data: [
            {
              playerId: 'player-1',
              slotType: 'XI',
              role: 'CAPTAIN',
              benchPriority: null,
            },
          ],
        },
      },
    })
  })
})
